name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello GitHub Actions!"
      - name: Present Working Dir info
        run: pwd
      - name: List Files and Dir
        run: ls -al
